name: API Snapshot

on:
  push:
    branches:
      - master
    paths: 
      - 'API/pom*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build with Maven
        run: mvn -B -pl API package | egrep -v "^\[INFO\].*?Download.*?http"

      - name: Publish to OSSRH
        run: mvn -B -pl API deploy | egrep -v "^\[INFO\].*?Download.*?http"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASS }}
